### ISSUE TITLE
Blender - Output File Path Issue

### ISSUE THREAD

**Issue by michaelsherwood** [BinaryAlchemy/RoyalRender-OpenExtensions#2]
I found an issue in the blender config that would cause my output file path to not place a '.' between the filename and the frame padding resulting in a path that looked like this:

```
path/to/file####.ext
```

I managed to fix the issue by changing the following line:
https://github.com/BinaryAlchemy/RoyalRender-OpenExtensions/blob/4b53a0a70cec795e827c5d4ae5c45dcf26e3dbfd/_render_app/Blender_v2/RR8/render_apps/_config/3D19__Blender.cfg#L37

```
-o "<ImageDir><ImageFilename><EL.><EL<PNL>><EL.>"
```

This change now gives the expected output path 

```
path/to/file.####.ext
```

**Comment by h-schoenberger** [comment]
-o "<ImageDir><ImageFilename>"
should be the right fix.

**Comment by michaelsherwood** [comment]
```-o ""```
This causes RR to only output the frame number and ext

```path/to/####.ext```
Which causes the `Disable - no frames found` error since RR is expecting the output to be ```path/to/file.####.ext```

**Comment by h-schoenberger** [comment]
Sorry, this website removed the variables

`-o "<ImageDir><ImageFilename>"`

**Comment by michaelsherwood** [comment]
Ended up getting to that shortly after my last reply.

Thanks for clearing up.
